#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Client.Resource", IsApplication=true)]

namespace Client
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CodeFile = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int TextFile = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Utility = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int XmlFile = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int CommandAdd = 2131099650;
			
			// aapt resource value: 0x7f06000c
			public const int CommandDescription = 2131099660;
			
			// aapt resource value: 0x7f060000
			public const int CommandList = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int CommandsNone = 2131099649;
			
			// aapt resource value: 0x7f060011
			public const int ConsoleCheckbox = 2131099665;
			
			// aapt resource value: 0x7f060003
			public const int ConsoleInput = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int ConsoleText = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int CreateCommandDescription = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int CreateCommandName = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int CreateFileField = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int CreateProject_Name = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int EditorField = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int EditorUtility = 2131099659;
			
			// aapt resource value: 0x7f060012
			public const int LoginPassword = 2131099666;
			
			// aapt resource value: 0x7f06000f
			public const int NoProcesses = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int ProcessContainer = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int ProcessList = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int ProcessName = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int SelectionList = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int WaitSpinner = 2131099668;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout1 = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Commands = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Console = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CreateCommand = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CreateFile = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CreateProject = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Editor = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Empty = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ExecuteLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Login = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SelectionDialog = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Wait = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int ClientTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ClientThemeDark = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
